### ISSUE TITLE
Default not handled

### ISSUE THREAD

**Issue by jerryzj** [jerryzj/Cache_sim#17]
https://github.com/jerryzj/Cache_sim/blob/74c8a725d7ae4808594826419e37265b635d523e/src/main_cache.cpp#L159

`default`  should be unreachable, you should throw exception or exit with abnormal code.

**Comment by jackyhuang85** [comment]
I fixed that by amending switch branching condition
commit: f8ab7ffde8b8049ccd27eb30df75dca352b4483c
